### ISSUE TITLE
gestion Auth: test sur meteor

### ISSUE THREAD

**Issue by guillim** [co-demos/ApiViz#16]
- Test pour connecter Meteor a la base Mongodb
 - mise ajour au dernieres version des package pour la securite

**Comment by guillim** [comment]
regarder ce projet: https://github.com/hharnisc/python-meteor

**Comment by JulienParis** [comment]
Meteor fonctionne avec le protocole web socket --> compliqué de mettre en place un protocole d'échange ApiViz (vue.js) - Meteor pour gérer uniquement les droits d'accès et l'authentification

**Comment by JulienParis** [comment]
décision de tester / forker soldats_backend pour en récupérer et mettre en place un micro service tiers d'authentification en API REST

**Comment by JulienParis** [comment]
mise en place du repo TokTok pour répondre à ce besoin d'authentification externalisé pour ApiViz : https://github.com/co-demos/toktok
