### ISSUE TITLE
bulma carousel integration

### ISSUE THREAD

**Issue by JulienParis** [co-demos/ApiViz#72]
cf :  https://github.com/entrepreneur-interet-general/CIS-front/pull/312

**Comment by CBalsier** [comment]
Done in commit https://github.com/co-demos/ApiViz/commit/979b3f05f37e390aac98b062a9eeccb54d10c3b0

cf. https://github.com/co-demos/ApiViz/blob/26e4eff839c60cba2941e8f021780202c6e4db5f/backend/frontend/scripts/utils.js#L267
